export const dummyNfts = [
  {
    name: "Founder's Pirate #196",
    description: "Founder's Pirate #196 _desc",
    image: "QmXdZNip1yYgxDmA4tG2PV5Qi2rupGf2fviTD3pFNubZLR",
    tokenUrl: "QmampA1c3jhXDbr191TAtcmkRx8wuKCJ6bjuvKwdMsKwYS",
    ext: "png",
  },
  {
    name: "Founder's Pirate #100",
    description: "Founder's Pirate #100 _desc",
    image: "QmUREQUpVC8M51sfHftHhiN84xWnQhUqzWgnkJFMhjcsFf",
    tokenUrl: "QmSt1KWcEZfpGu7BjALRSLAUVdu9VRQx9toFYDxWwhVaRa",
    ext: "png",
  },
  {
    name: "#000 doodle",
    description: "doodle_description",
    image: "QmfSyxLdtUnwPUBJEjmorqXiSHb7BRqF7yNWZevg3VDiXb",
    tokenUrl: "QmNgAeWzGfVyPQLb1w8aD3atxozdMAs3CiGPipXCzCYfBw",
    ext: "png",
  },
  {
    name: "#000 borning monkey",
    description:
      "borning borning monkey_desciptionborning monkey_desciptionborning monkey_desciptionborning monkey_desciptionmonkey_desciption",
    image: "QmXqKC7qCAU8sD8Rrw535HC2824c5EaGyHUtJcHBkVkeL2",
    tokenUrl: "QmRyxs2iGv4qSibs1V1zedEwh2jtakX15z931WSmrrD86P",
    ext: "png",
  },
  {
    name: "#000 jangkal cat",
    description:
      "jangkal cat_descriptionjangkal cat_descriptionjangkal cat_descriptionjangkal cat_descriptionjangkal cat_descriptionjangkal cat_description",
    image: "QmUCxQVTKVXKtcxnZsGRus8ydWkDEzam1WNQHjbqQjsoBe",
    tokenUrl: "QmRo8mUuzaSSAbWfKB6T7i398Qs8gqbPnYm4nH7TW6hu76",
    ext: "png",
  },
  {
    name: "51billion",
    description: "51billion_description",
    image: "QmdSGhWtyNDAQ7DRsDbipSx8Zm9pRP7NLJ8G9XudAdCgP5",
    tokenUrl: "QmVkyvvsZVwteaABWBAZ1GF3s8ufu88fvozmsEbzMYJJu1",
    ext: "png",
  },
  {
    name: "#003 Jack's NFT ",
    description: "A cute CryptoKitty that enjoys long walks on the beach.",
    image: "QmfSeLSMHsKrLMLe4Wh5n47YTggdirDvxiNKs1oijJVpNr",
    tokenUrl: "QmT5PCMQ52cnwF65E7j6QfmGtjGwjPk5Yq4qbw6epK2oni",
    ext: "png",
  },
  {
    name: "#002 Jack's NFT",
    description: "A cute CryptoKitty that enjoys long walks on the beach.",
    image: "QmU7PvbNYu5xnGezJhhvZF1WJDTR1j6bBw9RZdZAhHocLc",
    tokenUrl: "QmQmTKzxevqXZ39JueBgqkoXRdaTgAX4QN3JtuCWHRnPfFS5",
    ext: "png",
  },
  {
    name: "Remilio 4889",
    description: "Remilio 4889 _desc",
    image: "QmQWFtXsrCsgrtHFx8cEC5MqiADMM9WfcVQh2UcLhqsjJ1",
    tokenUrl: "QmXvJkkQpvzQqjKm8S4AD87FWKX6VhMi3aZYyQnkfMuSzp",
    ext: "png",
  },
  {
    name: "#000 onchain monkey",
    description: "onchain-monkey2 _desc",
    image: "QmVmWGi3obo6T8zCTbrvs4ZBMZWX1ry2ZT3WNQXjgvdAcn",
    tokenUrl: "QmYwD2H3o64N9VS3AMYyw6eLJxJ9xoxqnDmNWFazVMwijS",
    ext: "png",
  },
  {
    name: "Mutant Ape Yacht Club",
    description: "Mutant Ape Yacht Club _desc",
    image: "QmUgsKoTXzJ58sMqqX4iV8F6NVwQqsiK6NbACTkRDpFoYA",
    tokenUrl: "Qmc6ExSsQDs51X6gX4UpNQeEHiKJjTG3TpyjP7UzpnrZax",
    ext: "png",
  },
  {
    name: "Founder's Pirate #1096",
    description: "Founder's Pirate #1096 _desc",
    image: "QmVP6hymA5Udt3BC9ivyT39pmdjY3SZ6LHUcH9wyPrhvRB",
    tokenUrl: "QmdCVDKBwjSZHiGv8RNred2pNmrQ6XwLjqv1699MpGhYbx",
    ext: "png",
  },
  {
    name: "Remilio 2378",
    description: "Remilio 2378 _desc",
    image: "QmeaKdxtPaU6HaovqjAb46YQcYWymYtM8VJPVSZnEghRBL",
    tokenUrl: "QmdagPVRgZDAEmnfVasBFMujZcFTDqPeg27n39gLfucCTZ",
    ext: "png",
  },
  {
    name: "Remilio 881",
    description: "Remilio 881 _desc",
    image: "QmeNidW9SULbXeyi1fHFqA8x7zeEEbvtKhRkYwPGiCDr48",
    tokenUrl: "QmQmaCAQnsPKHAx6sdsEVhrXtbh6jWN6Q9fGWSMsna3wMznj",
    ext: "png",
  },
];
